import { NextResponse } from 'next/server'
import { db } from '@/lib/db'
import puppeteer from 'puppeteer'

export async function GET() {
  try {
    const endDate = new Date()
    const startDate = new Date()
    startDate.setDate(startDate.getDate() - 7)

    const tickets = await db.query<{
      ticket_id: string;
      title: string;
      category: string;
      priority: string;
      status: string;
      created_at: string;
    }>(
      `SELECT ticket_id, title, category, priority, status, created_at FROM tickets WHERE created_at BETWEEN datetime(?) AND datetime(?)`,
      [startDate.toISOString(), endDate.toISOString()]
    )

    const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #0066cc; text-align: center; }
        h2 { color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #0066cc; color: white; }
        .summary { background-color: #f0f8ff; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; margin-top: 30px; color: #666; }
      </style>
    </head>
    <body>
      <h1>KPA ICT Nexus - Weekly Report</h1>
      <p><strong>Report Period:</strong> ${startDate.toDateString()} - ${endDate.toDateString()}</p>
      
      <div class="summary">
        <h2>Executive Summary</h2>
        <p>Total Tickets This Week: ${tickets.length}</p>
        <p>Open Tickets: ${tickets.filter(t => t.status === 'open').length}</p>
        <p>Resolved Tickets: ${tickets.filter(t => t.status === 'resolved').length}</p>
      </div>
      
      <h2>Detailed Ticket List</h2>
      <table>
        <tr>
          <th>Ticket ID</th>
          <th>Title</th>
          <th>Category</th>
          <th>Priority</th>
          <th>Status</th>
          <th>Created Date</th>
        </tr>
        ${tickets.map(ticket => `
          <tr>
            <td>${ticket.ticket_id}</td>
            <td>${ticket.title}</td>
            <td>${ticket.category}</td>
            <td>${ticket.priority}</td>
            <td>${ticket.status}</td>
            <td>${new Date(ticket.created_at).toLocaleDateString()}</td>
          </tr>
        `).join('')}
      </table>
      
      <div class="footer">
        <p>Generated by KPA ICT Nexus System - ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>`

    // Launch Puppeteer with correct options
    const browser = await puppeteer.launch({
      headless: true, // Changed from 'new' to true
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    })
    const page = await browser.newPage()

    await page.setContent(html)
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm', left: '10mm', right: '10mm' }
    })

    await browser.close()

    // Convert Buffer to Response
    return new NextResponse(Buffer.from(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename=weekly-report.pdf'
      }
    })
  } catch (error) {
    console.error('Error generating PDF:', error)
    return NextResponse.json({ error: 'Error generating report' }, { status: 500 })
  }
}